package frontend.unit;

// Generated by Selenium IDE - Adapted for JUnit 5
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;

public class UIIngredientTest extends BaseUnitTest {
  private JavascriptExecutor js;

  private void jsClick(WebElement element) {
    js.executeScript("arguments[0].click();", element);
  }

  @BeforeEach
  public void setUpTest() {
    super.setUp();
    js = (JavascriptExecutor) driver;

    // Login with admin user
    driver.get("https://localhost:8443/login");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("login-username")).click();
    driver.findElement(By.id("login-username")).sendKeys("admin");
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.id("login-password")).sendKeys("adminpass");
    driver.findElement(By.id("loginBut")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.urlToBe("https://localhost:8443/"));

    // Wait for the main page to load fully after login
    wait.until(ExpectedConditions.urlToBe("https://localhost:8443/"));
  }
  @Test
  public void ingredientcrud() {
    // Test name: Ingredient CRUD - Create, Read, Update, Delete
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

    // ========== CREATE INGREDIENT ==========
    driver.get("https://localhost:8443/ingredients");
    driver.manage().window().setSize(new Dimension(2047, 944));

    // Navigated to ingredients

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".nav-item:nth-child(4)"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".tab:nth-child(2)")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".rounded-xl:nth-child(1)"))).click();

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".px-4")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    wait.until(ExpectedConditions.presenceOfElementLocated(By.name("food"))).sendKeys("Test Ingredient ZZZ");

    WebElement createBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn:nth-child(4)")));
    jsClick(createBtn);

    // Wait for creation to process
    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[contains(text(), 'Test Ingredient ZZZ')]")));

    // ========== EDIT INGREDIENT ==========
    driver.get("https://localhost:8443/ingredients");
    driver.manage().window().setSize(new Dimension(2047, 944));

    // Wait for page load

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".grid")));

    WebElement editBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".top-14 > .ti")));
    jsClick(editBtn);

    // Wait for edit click to process

    WebElement foodInput = wait.until(ExpectedConditions.presenceOfElementLocated(By.name("food")));
    foodInput.clear();
    foodInput.sendKeys("Updated Ingredient ZZZ");

    WebElement saveBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".btn > span")));
    jsClick(saveBtn);

    // Wait for save to complete before navigating again
    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[contains(text(), 'Updated Ingredient ZZZ')]")));

    // ========== DELETE INGREDIENT ==========
    driver.get("https://localhost:8443/ingredients");
    driver.manage().window().setSize(new Dimension(2047, 944));

    // After navigate

    wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".grid")));

    {
      WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".top-2 > .ti")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    WebElement deleteBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".top-2 > .ti")));
    jsClick(deleteBtn);

    // Ready to confirm delete

    WebElement confirmBtn = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".confirmDelete:nth-child(1) > .ti")));
    jsClick(confirmBtn);

    // Verify delete by ensuring it is gone from the main list
    wait.until(ExpectedConditions.invisibilityOfElementLocated(By.xpath("//*[contains(text(), 'Updated Ingredient ZZZ')]")));
  }
}
